import type { Metadata } from 'next'
import { Inter,Montserrat } from 'next/font/google'
import './globals.css'
import { PortfolioContextProvider } from '@/context/PortfolioContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <PortfolioContextProvider>
        <body className={`${inter.className} bg-bgColor max-w-[1400px] mx-auto text-textColor`}>{children}</body>
      </PortfolioContextProvider>
    </html>
  )
}
